### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by tlhunter** [jonnyzzz/TeamCity.GitHub#110]
I see a few very useful PR's for fixing many typo's. It sounds like the PR's may be incomplete, but I don't see the author making any effort to fix the typo's separately.

Is this project abandoned? Does anyone have a maintained fork? If a fork were made would others want to use it?

**Comment by jonnyzzz** [comment]
Well, fixing typos in internal parameters which are not shown to the user is not a critical production issue overall. It was a failure to overseen those typos at the very beginning. Currently, I do not see it necessary to fix because of complexity and a huge number of corner cases. Any way, those properties are not shown in UI. There are contributors who tried, I'd like to say thank you to them all. Unfortunately, it's a bit tricky to fix it in the right way. I commented all such PR with details. Worth reading.

The project looks more less feature complete. It'd be great if there'll be someone to continue an active development of the project. For what goal? Nowadays, there is similar functionality embedded into TeamCity 10.0+.
